// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxuzdcUZI_RndLtUUlXOHMHS6zJJuLYj8',
    appId: '1:43479692933:web:e7cbd01d42d90468399bec',
    messagingSenderId: '43479692933',
    projectId: 'chat-app-1c062',
    authDomain: 'chat-app-1c062.firebaseapp.com',
    storageBucket: 'chat-app-1c062.firebasestorage.app',
    measurementId: 'G-1N2TSK0D1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEtAlMgFA_xB_7bnyq7cLl6tNlsACJ3U4',
    appId: '1:43479692933:android:6a3bb163b95a9c8d399bec',
    messagingSenderId: '43479692933',
    projectId: 'chat-app-1c062',
    storageBucket: 'chat-app-1c062.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfYeqA8BoMa5N8-LNHgdddgE5fUhTvB-A',
    appId: '1:43479692933:ios:04337fbd09ec53d8399bec',
    messagingSenderId: '43479692933',
    projectId: 'chat-app-1c062',
    storageBucket: 'chat-app-1c062.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfYeqA8BoMa5N8-LNHgdddgE5fUhTvB-A',
    appId: '1:43479692933:ios:04337fbd09ec53d8399bec',
    messagingSenderId: '43479692933',
    projectId: 'chat-app-1c062',
    storageBucket: 'chat-app-1c062.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxuzdcUZI_RndLtUUlXOHMHS6zJJuLYj8',
    appId: '1:43479692933:web:3ae4a4f5952682a6399bec',
    messagingSenderId: '43479692933',
    projectId: 'chat-app-1c062',
    authDomain: 'chat-app-1c062.firebaseapp.com',
    storageBucket: 'chat-app-1c062.firebasestorage.app',
    measurementId: 'G-5QQQF8YY5X',
  );
}
